name: Update News

on:
  schedule:
    - cron: '10 * * * *'  # 每小时的第10分钟运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update_news:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. 检查当前目录
    - name: Check current directory
      run: pwd

    # 3. 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 4. 安装依赖
    - name: Install dependencies
      run: |
        pwd  # 确保在正确的目录
        ls -la  # 确保 requirements.txt 存在
        pip install -r requirements.txt  # 安装依赖

    # 5. 运行爬虫脚本
    - name: Run the scraper
      run: python3 scraper.py

    # 6. 配置 Git
    - name: Configure Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

    # 7. 检查并提交更改
    - name: Commit changes
      run: |
        if git diff --quiet && git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git add news.json
          git commit -m "更新新闻数据"
          git push origin main
        fi
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
