name: Update News

on:
  schedule:
    # 每小时运行一次
    - cron: '10 * * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  update_news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 设置 Python 版本

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the scraper
      run: python3 scraper.py  # 假设爬虫脚本是 scraper.py

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add news.json
        git commit -m "更新新闻数据"
        git push
